export interface ImmigrationMethod {
  id: string
  name: string
  description: string
  duration: string
  cost: string
  requirements: string[]
  successRate: number
  difficulty: "easy" | "medium" | "hard"
  category: "education" | "work" | "investment" | "family" | "special"
}

export interface Country {
  id: string
  name: string
  englishName: string
  continent: string
  flagUrl: string
  description: string
  popularityRank: number
  methods: ImmigrationMethod[]
  livingCost: {
    housing: number
    food: number
    transport: number
    healthcare: number
    education: number
  }
  averageSalary: number
  language: string[]
  climate: string
  currency: string
  capital: string
  population: string
  gdp: string
}

export const immigrationMethods: Record<string, ImmigrationMethod> = {
  education: {
    id: "education",
    name: "مهاجرت تحصیلی",
    description: "تحصیل در دانشگاه‌های معتبر و اخذ ویزای تحصیلی",
    duration: "6-12 ماه",
    cost: "5,000-25,000",
    requirements: ["مدرک تحصیلی", "مدرک زبان", "تمکن مالی", "پذیرش دانشگاه"],
    successRate: 85,
    difficulty: "medium",
    category: "education",
  },
  work: {
    id: "work",
    name: "مهاجرت کاری",
    description: "اخذ ویزای کار و جاب آفر",
    duration: "8-18 ماه",
    cost: "3,000-15,000",
    requirements: ["تجربه کاری", "مدرک زبان", "مهارت تخصصی", "جاب آفر"],
    successRate: 75,
    difficulty: "hard",
    category: "work",
  },
  skilledWorker: {
    id: "skilledWorker",
    name: "نیروی متخصص",
    description: "مهاجرت برای متخصصان و نیروهای ماهر",
    duration: "6-15 ماه",
    cost: "4,000-18,000",
    requirements: ["تخصص مورد نیاز", "تجربه کاری", "مدرک زبان", "ارزیابی مدرک"],
    successRate: 78,
    difficulty: "hard",
    category: "work",
  },
  jobOffer: {
    id: "jobOffer",
    name: "پیشنهاد شغلی",
    description: "مهاجرت با داشتن پیشنهاد کار از کارفرما",
    duration: "4-10 ماه",
    cost: "2,000-12,000",
    requirements: ["پیشنهاد کار معتبر", "تأیید کارفرما", "مدرک زبان"],
    successRate: 85,
    difficulty: "medium",
    category: "work",
  },
  internship: {
    id: "internship",
    name: "کارآموزی",
    description: "برنامه‌های کارآموزی و تجربه کاری",
    duration: "3-8 ماه",
    cost: "1,500-8,000",
    requirements: ["پذیرش در برنامه", "مدرک تحصیلی", "بیمه"],
    successRate: 80,
    difficulty: "medium",
    category: "work",
  },
  investment: {
    id: "investment",
    name: "مهاجرت سرمایه‌گذاری",
    description: "سرمایه‌گذاری در املاک یا کسب‌وکار",
    duration: "3-8 ماه",
    cost: "250,000-500,000",
    requirements: ["سرمایه کافی", "منابع مالی قانونی", "طرح کسب‌وکار"],
    successRate: 90,
    difficulty: "easy",
    category: "investment",
  },
  goldenVisa: {
    id: "goldenVisa",
    name: "گلدن ویزا / ویزای طلایی",
    description: "خرید ملک برای اخذ اقامت",
    duration: "2-6 ماه",
    cost: "280,000-500,000",
    requirements: ["خرید ملک", "بیمه درمانی", "عدم سوء پیشینه"],
    successRate: 95,
    difficulty: "easy",
    category: "investment",
  },
  startup: {
    id: "startup",
    name: "ویزای استارت‌آپ",
    description: "راه‌اندازی کسب‌وکار نوآورانه",
    duration: "6-12 ماه",
    cost: "10,000-50,000",
    requirements: ["ایده نوآورانه", "طرح کسب‌وکار", "حمایت سرمایه‌گذار"],
    successRate: 70,
    difficulty: "hard",
    category: "investment",
  },
  entrepreneur: {
    id: "entrepreneur",
    name: "کارآفرینی",
    description: "راه‌اندازی کسب‌وکار و ثبت شرکت",
    duration: "4-10 ماه",
    cost: "15,000-75,000",
    requirements: ["طرح کسب‌وکار", "سرمایه اولیه", "تجربه مدیریتی"],
    successRate: 72,
    difficulty: "hard",
    category: "investment",
  },
  franchise: {
    id: "franchise",
    name: "خرید فرانچایز",
    description: "خرید حق نمایندگی برندهای معتبر",
    duration: "3-8 ماه",
    cost: "50,000-200,000",
    requirements: ["سرمایه کافی", "تأیید فرانچایز", "تجربه کسب‌وکار"],
    successRate: 82,
    difficulty: "medium",
    category: "investment",
  },
  businessPurchase: {
    id: "businessPurchase",
    name: "خرید بیزنس",
    description: "خرید کسب‌وکار موجود",
    duration: "2-6 ماه",
    cost: "100,000-500,000",
    requirements: ["ارزیابی کسب‌وکار", "منابع مالی", "تجربه مدیریتی"],
    successRate: 85,
    difficulty: "medium",
    category: "investment",
  },
  family: {
    id: "family",
    name: "مهاجرت خانوادگی",
    description: "پیوستن به اعضای خانواده",
    duration: "12-24 ماه",
    cost: "2,000-8,000",
    requirements: ["رابطه خانوادگی", "اسپانسر", "مدارک هویتی"],
    successRate: 80,
    difficulty: "medium",
    category: "family",
  },
  marriage: {
    id: "marriage",
    name: "مهاجرت از طریق ازدواج",
    description: "ازدواج با شهروند یا اقامت‌دار",
    duration: "8-18 ماه",
    cost: "3,000-10,000",
    requirements: ["گواهی ازدواج", "اثبات رابطه", "مدارک هویتی"],
    successRate: 85,
    difficulty: "medium",
    category: "family",
  },
  birth: {
    id: "birth",
    name: "مهاجرت از طریق تولد",
    description: "اخذ شهروندی بر اساس محل تولد",
    duration: "6-12 ماه",
    cost: "1,000-5,000",
    requirements: ["گواهی تولد", "مدارک والدین", "اثبات هویت"],
    successRate: 90,
    difficulty: "easy",
    category: "special",
  },
  asylum: {
    id: "asylum",
    name: "پناهندگی",
    description: "درخواست پناهندگی",
    duration: "12-36 ماه",
    cost: "1,000-5,000",
    requirements: ["دلایل پناهندگی", "مدارک مثبته", "مشاوره حقوقی"],
    successRate: 60,
    difficulty: "hard",
    category: "special",
  },
  specialPersons: {
    id: "specialPersons",
    name: "مهاجرت اشخاص خاص",
    description: "برای افراد با شرایط خاص",
    duration: "6-15 ماه",
    cost: "3,000-15,000",
    requirements: ["شرایط خاص", "مدارک مثبته", "تأیید مراجع"],
    successRate: 75,
    difficulty: "medium",
    category: "special",
  },
  ausbildung: {
    id: "ausbildung",
    name: "آوسبیلدونگ آلمان",
    description: "آموزش حرفه‌ای در آلمان",
    duration: "4-8 ماه",
    cost: "2,000-5,000",
    requirements: ["زبان آلمانی B1", "مدرک دیپلم", "انگیزه‌نامه"],
    successRate: 88,
    difficulty: "medium",
    category: "education",
  },
  jobSeeker: {
    id: "jobSeeker",
    name: "ویزای جستجو کار",
    description: "ویزا برای جستجوی کار",
    duration: "2-6 ماه",
    cost: "1,500-5,000",
    requirements: ["مدرک تحصیلی", "مدرک زبان", "تمکن مالی"],
    successRate: 70,
    difficulty: "medium",
    category: "work",
  },
  financialSufficiency: {
    id: "financialSufficiency",
    name: "اقامت تمکن مالی",
    description: "اقامت بر اساس توانایی مالی",
    duration: "3-8 ماه",
    cost: "50,000-150,000",
    requirements: ["اثبات درآمد", "حساب بانکی", "بیمه درمانی"],
    successRate: 85,
    difficulty: "medium",
    category: "investment",
  },
  selfEmployment: {
    id: "selfEmployment",
    name: "ثبت شرکت و خوداشتغالی",
    description: "ثبت شرکت و کار آزاد",
    duration: "2-6 ماه",
    cost: "5,000-25,000",
    requirements: ["طرح کسب‌وکار", "سرمایه اولیه", "مجوزهای لازم"],
    successRate: 75,
    difficulty: "medium",
    category: "investment",
  },
  studentVisa: {
    id: "studentVisa",
    name: "ویزای دانش‌آموزی",
    description: "ویزا برای تحصیل در مقاطع پایین‌تر",
    duration: "3-8 ماه",
    cost: "3,000-12,000",
    requirements: ["پذیرش مدرسه", "تمکن مالی", "سرپرست قانونی"],
    successRate: 80,
    difficulty: "medium",
    category: "education",
  },
}

export const countries: Country[] = [
  {
    id: "germany",
    name: "آلمان",
    englishName: "Germany",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/de.svg",
    description: "بزرگترین اقتصاد اروپا با فرصت‌های شغلی عالی و سیستم آموزشی پیشرفته",
    popularityRank: 1,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.jobOffer,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
      immigrationMethods.ausbildung,
      immigrationMethods.jobSeeker,
      immigrationMethods.entrepreneur,
    ],
    livingCost: { housing: 800, food: 300, transport: 100, healthcare: 200, education: 0 },
    averageSalary: 3500,
    language: ["آلمانی"],
    climate: "معتدل",
    currency: "یورو",
    capital: "برلین",
    population: "83 میلیون",
    gdp: "4.26 تریلیون دلار",
  },
  {
    id: "austria",
    name: "اتریش",
    englishName: "Austria",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/at.svg",
    description: "کیفیت زندگی بالا و مناظر زیبای آلپ",
    popularityRank: 6,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 750, food: 320, transport: 110, healthcare: 220, education: 1500 },
    averageSalary: 3200,
    language: ["آلمانی"],
    climate: "قاره‌ای",
    currency: "یورو",
    capital: "وین",
    population: "9 میلیون",
    gdp: "481 میلیارد دلار",
  },
  {
    id: "italy",
    name: "ایتالیا",
    englishName: "Italy",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/it.svg",
    description: "تاریخ غنی، فرهنگ بی‌نظیر و آب و هوای مدیترانه‌ای",
    popularityRank: 7,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
      immigrationMethods.selfEmployment,
    ],
    livingCost: { housing: 650, food: 280, transport: 85, healthcare: 160, education: 4000 },
    averageSalary: 2200,
    language: ["ایتالیایی"],
    climate: "مدیترانه‌ای",
    currency: "یورو",
    capital: "رم",
    population: "60 میلیون",
    gdp: "2.11 تریلیون دلار",
  },
  {
    id: "spain",
    name: "اسپانیا",
    englishName: "Spain",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/es.svg",
    description: "فرهنگ غنی، آب و هوای آفتابی و گلدن ویزای جذاب",
    popularityRank: 4,
    methods: [
      immigrationMethods.goldenVisa,
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 700, food: 300, transport: 90, healthcare: 180, education: 8000 },
    averageSalary: 1800,
    language: ["اسپانیایی"],
    climate: "مدیترانه‌ای",
    currency: "یورو",
    capital: "مادرید",
    population: "47 میلیون",
    gdp: "1.42 تریلیون دلار",
  },
  {
    id: "france",
    name: "فرانسه",
    englishName: "France",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/fr.svg",
    description: "مرکز فرهنگ و هنر اروپا با سیستم آموزشی معتبر",
    popularityRank: 8,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.investment,
      immigrationMethods.startup,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 900, food: 350, transport: 120, healthcare: 200, education: 10000 },
    averageSalary: 2800,
    language: ["فرانسوی"],
    climate: "معتدل",
    currency: "یورو",
    capital: "پاریس",
    population: "68 میلیون",
    gdp: "2.94 تریلیون دلار",
  },
  {
    id: "portugal",
    name: "پرتغال",
    englishName: "Portugal",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/pt.svg",
    description: "آب و هوای عالی، گلدن ویزای جذاب و هزینه زندگی مناسب",
    popularityRank: 3,
    methods: [
      immigrationMethods.goldenVisa,
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 600, food: 250, transport: 80, healthcare: 150, education: 5000 },
    averageSalary: 1200,
    language: ["پرتغالی"],
    climate: "مدیترانه‌ای",
    currency: "یورو",
    capital: "لیسبون",
    population: "10.3 میلیون",
    gdp: "253 میلیارد دلار",
  },
  {
    id: "sweden",
    name: "سوئد",
    englishName: "Sweden",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/se.svg",
    description: "کشور پیشرفته با رفاه اجتماعی بالا و نوآوری",
    popularityRank: 9,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 1000, food: 400, transport: 120, healthcare: 0, education: 0 },
    averageSalary: 3800,
    language: ["سوئدی"],
    climate: "سرد",
    currency: "کرون سوئد",
    capital: "استکهلم",
    population: "10.4 میلیون",
    gdp: "635 میلیارد دلار",
  },
  {
    id: "switzerland",
    name: "سوئیس",
    englishName: "Switzerland",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/ch.svg",
    description: "بالاترین کیفیت زندگی و درآمد در اروپا",
    popularityRank: 10,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 1500, food: 600, transport: 150, healthcare: 300, education: 20000 },
    averageSalary: 6500,
    language: ["آلمانی", "فرانسوی", "ایتالیایی"],
    climate: "کوهستانی",
    currency: "فرانک سوئیس",
    capital: "برن",
    population: "8.7 میلیون",
    gdp: "812 میلیارد دلار",
  },
  {
    id: "cyprus",
    name: "قبرس",
    englishName: "Cyprus",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/cy.svg",
    description: "جزیره زیبای مدیترانه با گلدن ویزای جذاب",
    popularityRank: 11,
    methods: [
      immigrationMethods.goldenVisa,
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 500, food: 200, transport: 60, healthcare: 120, education: 6000 },
    averageSalary: 1500,
    language: ["یونانی", "ترکی"],
    climate: "مدیترانه‌ای",
    currency: "یورو",
    capital: "نیکوزیا",
    population: "1.2 میلیون",
    gdp: "27 میلیارد دلار",
  },
  {
    id: "denmark",
    name: "دانمارک",
    englishName: "Denmark",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/dk.svg",
    description: "کشور شاد با رفاه اجتماعی بالا و فرصت‌های شغلی عالی",
    popularityRank: 12,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 1100, food: 450, transport: 130, healthcare: 0, education: 0 },
    averageSalary: 4200,
    language: ["دانمارکی"],
    climate: "معتدل",
    currency: "کرون دانمارک",
    capital: "کپنهاگ",
    population: "5.8 میلیون",
    gdp: "395 میلیارد دلار",
  },
  {
    id: "norway",
    name: "نروژ",
    englishName: "Norway",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/no.svg",
    description: "کشور ثروتمند با منابع نفتی و کیفیت زندگی بالا",
    popularityRank: 13,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 1200, food: 500, transport: 140, healthcare: 0, education: 0 },
    averageSalary: 5000,
    language: ["نروژی"],
    climate: "سرد",
    currency: "کرون نروژ",
    capital: "اسلو",
    population: "5.4 میلیون",
    gdp: "482 میلیارد دلار",
  },
  {
    id: "belgium",
    name: "بلژیک",
    englishName: "Belgium",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/be.svg",
    description: "مرکز اتحادیه اروپا با فرصت‌های شغلی متنوع",
    popularityRank: 14,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 800, food: 350, transport: 100, healthcare: 200, education: 5000 },
    averageSalary: 3000,
    language: ["هلندی", "فرانسوی", "آلمانی"],
    climate: "معتدل",
    currency: "یورو",
    capital: "بروکسل",
    population: "11.5 میلیون",
    gdp: "594 میلیارد دلار",
  },
  {
    id: "croatia",
    name: "کرواسی",
    englishName: "Croatia",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/hr.svg",
    description: "ساحل زیبای آدریاتیک و عضو جدید اتحادیه اروپا",
    popularityRank: 15,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 400, food: 200, transport: 60, healthcare: 100, education: 3000 },
    averageSalary: 1000,
    language: ["کرواتی"],
    climate: "مدیترانه‌ای",
    currency: "یورو",
    capital: "زاگرب",
    population: "3.9 میلیون",
    gdp: "70 میلیارد دلار",
  },
  {
    id: "hungary",
    name: "مجارستان",
    englishName: "Hungary",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/hu.svg",
    description: "کشور تاریخی با هزینه زندگی مناسب در قلب اروپا",
    popularityRank: 16,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 350, food: 180, transport: 50, healthcare: 80, education: 2500 },
    averageSalary: 800,
    language: ["مجاری"],
    climate: "قاره‌ای",
    currency: "فورینت",
    capital: "بوداپست",
    population: "9.7 میلیون",
    gdp: "181 میلیارد دلار",
  },
  {
    id: "netherlands",
    name: "هلند",
    englishName: "Netherlands",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/nl.svg",
    description: "کشور پیشرفته با اقتصاد قوی و فرهنگ آزاد",
    popularityRank: 17,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.startup,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 1000, food: 400, transport: 120, healthcare: 150, education: 12000 },
    averageSalary: 3500,
    language: ["هلندی"],
    climate: "معتدل",
    currency: "یورو",
    capital: "آمستردام",
    population: "17.4 میلیون",
    gdp: "1.01 تریلیون دلار",
  },
  {
    id: "uk",
    name: "انگلیس",
    englishName: "United Kingdom",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/gb.svg",
    description: "کشور قدرتمند با سیستم آموزشی معتبر جهانی",
    popularityRank: 18,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.startup,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 1200, food: 450, transport: 150, healthcare: 0, education: 25000 },
    averageSalary: 3800,
    language: ["انگلیسی"],
    climate: "معتدل",
    currency: "پوند",
    capital: "لندن",
    population: "67 میلیون",
    gdp: "3.13 تریلیون دلار",
  },
  {
    id: "finland",
    name: "فنلاند",
    englishName: "Finland",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/fi.svg",
    description: "کشور شاد با سیستم آموزشی برتر جهان",
    popularityRank: 19,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 900, food: 400, transport: 110, healthcare: 0, education: 0 },
    averageSalary: 3600,
    language: ["فنلاندی", "سوئدی"],
    climate: "سرد",
    currency: "یورو",
    capital: "هلسینکی",
    population: "5.5 میلیون",
    gdp: "297 میلیارد دلار",
  },
  {
    id: "canada",
    name: "کانادا",
    englishName: "Canada",
    continent: "آمریکای شمالی",
    flagUrl: "https://flagcdn.com/ca.svg",
    description: "کشور مهاجرپذیر با سیستم مهاجرتی شفاف و کیفیت زندگی بالا",
    popularityRank: 2,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.startup,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 1200, food: 400, transport: 150, healthcare: 0, education: 15000 },
    averageSalary: 4000,
    language: ["انگلیسی", "فرانسوی"],
    climate: "سرد",
    currency: "دلار کانادا",
    capital: "اتاوا",
    population: "38 میلیون",
    gdp: "2.14 تریلیون دلار",
  },
  {
    id: "usa",
    name: "آمریکا",
    englishName: "United States",
    continent: "آمریکای شمالی",
    flagUrl: "https://flagcdn.com/us.svg",
    description: "بزرگترین اقتصاد جهان با فرصت‌های بی‌نظیر",
    popularityRank: 20,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.startup,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 1500, food: 500, transport: 200, healthcare: 400, education: 30000 },
    averageSalary: 5000,
    language: ["انگلیسی"],
    climate: "متنوع",
    currency: "دلار آمریکا",
    capital: "واشنگتن",
    population: "331 میلیون",
    gdp: "26.9 تریلیون دلار",
  },
  {
    id: "uae",
    name: "امارات",
    englishName: "United Arab Emirates",
    continent: "خاورمیانه",
    flagUrl: "https://flagcdn.com/ae.svg",
    description: "مرکز تجاری خاورمیانه با فرصت‌های شغلی عالی",
    popularityRank: 21,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.investment,
      immigrationMethods.goldenVisa,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 1000, food: 300, transport: 100, healthcare: 200, education: 8000 },
    averageSalary: 3000,
    language: ["عربی", "انگلیسی"],
    climate: "گرم و خشک",
    currency: "درهم امارات",
    capital: "ابوظبی",
    population: "10 میلیون",
    gdp: "507 میلیارد دلار",
  },
  {
    id: "dominica",
    name: "دومینیکا",
    englishName: "Dominica",
    continent: "کارائیب",
    flagUrl: "https://flagcdn.com/dm.svg",
    description: "جزیره زیبای کارائیب با برنامه شهروندی از طریق سرمایه‌گذاری",
    popularityRank: 22,
    methods: [
      immigrationMethods.investment,
      immigrationMethods.goldenVisa,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
    ],
    livingCost: { housing: 400, food: 200, transport: 50, healthcare: 100, education: 3000 },
    averageSalary: 800,
    language: ["انگلیسی"],
    climate: "استوایی",
    currency: "دلار کارائیب شرقی",
    capital: "روزو",
    population: "72 هزار",
    gdp: "0.6 میلیارد دلار",
  },
  {
    id: "oman",
    name: "عمان",
    englishName: "Oman",
    continent: "خاورمیانه",
    flagUrl: "https://flagcdn.com/om.svg",
    description: "کشور آرام خلیج فارس با فرهنگ غنی",
    popularityRank: 23,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 600, food: 200, transport: 80, healthcare: 150, education: 4000 },
    averageSalary: 1500,
    language: ["عربی"],
    climate: "گرم و خشک",
    currency: "ریال عمان",
    capital: "مسقط",
    population: "5.1 میلیون",
    gdp: "104 میلیارد دلار",
  },
  {
    id: "turkey",
    name: "ترکیه",
    englishName: "Turkey",
    continent: "آسیا/اروپا",
    flagUrl: "https://flagcdn.com/tr.svg",
    description: "موقعیت استراتژیک، شهروندی سریع و هزینه زندگی مناسب",
    popularityRank: 5,
    methods: [
      immigrationMethods.investment,
      immigrationMethods.goldenVisa,
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 400, food: 200, transport: 50, healthcare: 100, education: 3000 },
    averageSalary: 800,
    language: ["ترکی"],
    climate: "متنوع",
    currency: "لیر ترکیه",
    capital: "آنکارا",
    population: "84 میلیون",
    gdp: "819 میلیارد دلار",
  },
  {
    id: "greece",
    name: "یونان",
    englishName: "Greece",
    continent: "اروپا",
    flagUrl: "https://flagcdn.com/gr.svg",
    description: "مهد تمدن غرب با گلدن ویزای جذاب",
    popularityRank: 24,
    methods: [
      immigrationMethods.goldenVisa,
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 500, food: 250, transport: 70, healthcare: 120, education: 4000 },
    averageSalary: 1100,
    language: ["یونانی"],
    climate: "مدیترانه‌ای",
    currency: "یورو",
    capital: "آتن",
    population: "10.7 میلیون",
    gdp: "214 میلیارد دلار",
  },
  {
    id: "australia",
    name: "استرالیا",
    englishName: "Australia",
    continent: "اقیانوسیه",
    flagUrl: "https://flagcdn.com/au.svg",
    description: "کشور پیشرفته با کیفیت زندگی بالا و فرصت‌های شغلی عالی",
    popularityRank: 25,
    methods: [
      immigrationMethods.education,
      immigrationMethods.work,
      immigrationMethods.skilledWorker,
      immigrationMethods.investment,
      immigrationMethods.family,
      immigrationMethods.marriage,
      immigrationMethods.birth,
      immigrationMethods.asylum,
      immigrationMethods.specialPersons,
    ],
    livingCost: { housing: 1300, food: 450, transport: 160, healthcare: 200, education: 20000 },
    averageSalary: 4500,
    language: ["انگلیسی"],
    climate: "متنوع",
    currency: "دلار استرالیا",
    capital: "کانبرا",
    population: "25.7 میلیون",
    gdp: "1.55 تریلیون دلار",
  },
]

// Social Media Links
export const socialMediaLinks = {
  tiktok: "https://www.tiktok.com/@user1529530401152",
  telegram: "https://t.me/diacoeuat",
  instagram: {
    main: "https://www.instagram.com/diaco_Immigration",
    consulting: "https://www.instagram.com/diaco.Consulting",
  },
  soundcloud: "https://soundcloud.com/diaco-consulting",
  vimeo: "https://vimeo.com/user196262480",
  youtube: "https://www.youtube.com/@diaco-Holding",
  linkedin:
    "https://www.linkedin.com/in/%D9%87%D9%84%D8%AF%DB%8C%D9%86%DA%AF-%D9%85%D9%87%D8%A7%D8%AC%D8%B1%D8%AA%DB%8C-%D8%AF%DB%8C%D8%A7%DA%A9%D9%88-55575243/",
  pinterest: "https://pinterest.com/diacoconsulting/",
  twitter: "https://x.com/diacoeu1",
  facebook: "https://www.facebook.com/peywand.austria",
}

// Contact Information
export const contactInfo = {
  phone: "021-8807-3287",
  email: "info@diaco.eu",
  website: "diaco.eu",
  address: "تهران، ایران",
}

// Helper functions
export const getCountryById = (id: string): Country | undefined => {
  return countries.find((country) => country.id === id)
}

export const getMethodById = (id: string): ImmigrationMethod | undefined => {
  return Object.values(immigrationMethods).find((method) => method.id === id)
}

export const getCountriesByContinent = (continent: string): Country[] => {
  return countries.filter((country) => country.continent === continent)
}

export const getMethodsByCategory = (category: string): ImmigrationMethod[] => {
  return Object.values(immigrationMethods).filter((method) => method.category === category)
}

export const getPopularCountries = (limit = 10): Country[] => {
  return countries.sort((a, b) => a.popularityRank - b.popularityRank).slice(0, limit)
}
