export type MigrationMethod = {
  id: string
  title: string
  description: string
  processDuration: string
  averageCost: string
  visaTypes?: string[]
  jobOpportunities?: string[]
  educationSystem?: string
  costOfLiving?: string
  startupSupport?: string
  selfEmploymentOptions?: string
  jobSearchVisa?: string
  marriageVisa?: string
  birthrightCitizenship?: string
  asylumProcess?: string
}

export type Country = {
  id: string
  name: string
  flagUrl?: string
  description: string
  migrationMethods: MigrationMethod[]
  continent: string
  capital: string
  population: string
  currency: string
  language: string
  climate: string
  socialAmenities: string[]
}

export const countries: Country[] = [
  {
    id: "CAN",
    name: "کانادا",
    flagUrl: "https://flagcdn.com/ca.svg",
    description:
      "کانادا یکی از محبوب‌ترین مقاصد مهاجرتی در جهان است که به دلیل سیاست‌های مهاجرتی باز، اقتصاد قوی، سیستم آموزشی عالی و کیفیت بالای زندگی شناخته شده است. این کشور فرصت‌های شغلی فراوانی در بخش‌های فناوری، بهداشت و درمان و منابع طبیعی ارائه می‌دهد.",
    migrationMethods: [
      {
        id: "express-entry",
        title: "اکسپرس انتری",
        description: "سیستم مهاجرت کاری مبتنی بر امتیاز برای کارگران ماهر.",
        processDuration: "6-12 ماه",
        averageCost: "2,300 CAD",
        visaTypes: ["Permanent Resident Visa"],
        jobOpportunities: ["IT", "Healthcare", "Engineering"],
        educationSystem: "High quality, publicly funded",
        costOfLiving: "Moderate to High",
      },
      {
        id: "pnp",
        title: "برنامه‌های نامزدی استانی (PNP)",
        description: "برنامه‌های مهاجرتی خاص هر استان برای جذب نیروی کار مورد نیاز.",
        processDuration: "12-18 ماه",
        averageCost: "1,500 CAD",
        visaTypes: ["Permanent Resident Visa"],
        jobOpportunities: ["Varies by province"],
        educationSystem: "High quality, publicly funded",
        costOfLiving: "Varies by province",
      },
      {
        id: "study-permit",
        title: "ویزای تحصیلی",
        description: "امکان تحصیل در دانشگاه‌ها و کالج‌های کانادا و کار پس از فارغ‌التحصیلی.",
        processDuration: "3-6 ماه",
        averageCost: "1,000 CAD (application fee)",
        visaTypes: ["Study Permit"],
        jobOpportunities: ["Part-time during study, Post-Graduation Work Permit"],
        educationSystem: "World-class universities",
        costOfLiving: "Moderate to High",
      },
      {
        id: "startup-visa",
        title: "ویزای استارت‌آپ",
        description: "برای کارآفرینانی که پتانسیل ایجاد کسب‌وکار نوآورانه در کانادا را دارند.",
        processDuration: "12-16 ماه",
        averageCost: "2,075 CAD",
        visaTypes: ["Permanent Resident Visa"],
        startupSupport: "Strong ecosystem, incubators",
      },
      {
        id: "family-sponsorship",
        title: "اسپانسرشیپ خانوادگی",
        description: "امکان پیوستن اعضای خانواده به شهروندان یا مقیمان دائم کانادا.",
        processDuration: "12-24 ماه",
        averageCost: "1,080 CAD",
        visaTypes: ["Permanent Resident Visa"],
      },
      {
        id: "asylum",
        title: "پناهندگی",
        description: "حمایت از افرادی که در کشور خود در معرض خطر هستند.",
        processDuration: "Varies",
        averageCost: "Low (legal fees may apply)",
        asylumProcess: "Complex legal process",
      },
    ],
    continent: "آمریکای شمالی",
    capital: "اتاوا",
    population: "38 میلیون",
    currency: "دلار کانادا",
    language: "انگلیسی، فرانسوی",
    climate: "متنوع (سرد در زمستان، معتدل در تابستان)",
    socialAmenities: ["Healthcare", "Education", "Public Transport"],
  },
  {
    id: "DEU",
    name: "آلمان",
    flagUrl: "https://flagcdn.com/de.svg",
    description:
      "آلمان به عنوان بزرگترین اقتصاد اروپا، فرصت‌های شغلی فراوانی را در صنایع مهندسی، خودروسازی و فناوری اطلاعات ارائه می‌دهد. سیستم آموزشی رایگان و کیفیت بالای زندگی از دیگر مزایای این کشور است.",
    migrationMethods: [
      {
        id: "blue-card",
        title: "بلو کارت اتحادیه اروپا",
        description: "ویزای کار برای متخصصان با تحصیلات عالی و درآمد بالا.",
        processDuration: "2-4 ماه",
        averageCost: "110 EUR",
        visaTypes: ["EU Blue Card"],
        jobOpportunities: ["Engineering", "IT", "Healthcare"],
        educationSystem: "High quality, often free",
        costOfLiving: "Moderate",
      },
      {
        id: "job-seeker-visa",
        title: "ویزای جستجوی کار",
        description: "امکان ورود به آلمان برای جستجوی کار به مدت 6 ماه.",
        processDuration: "2-3 ماه",
        averageCost: "75 EUR",
        visaTypes: ["Job Seeker Visa"],
        jobSearchVisa: "6-month validity",
      },
      {
        id: "ausbildung",
        title: "آوسبیلدونگ",
        description: "دوره‌های آموزشی حرفه‌ای و کارورزی با حقوق در آلمان.",
        processDuration: "3-6 ماه",
        averageCost: "75 EUR (visa fee)",
        visaTypes: ["National Visa (D-Visa)"],
        jobOpportunities: ["Vocational training, guaranteed job"],
        educationSystem: "Dual vocational training system",
        costOfLiving: "Low to Moderate",
      },
      {
        id: "study-visa",
        title: "ویزای تحصیلی",
        description: "تحصیل در دانشگاه‌های دولتی آلمان که اغلب رایگان هستند.",
        processDuration: "2-3 ماه",
        averageCost: "75 EUR (visa fee)",
        visaTypes: ["Student Visa"],
        educationSystem: "Excellent, often tuition-free",
        costOfLiving: "Moderate",
      },
      {
        id: "family-reunion",
        title: "ویزای پیوست به خانواده",
        description: "برای پیوستن به همسر یا والدین مقیم آلمان.",
        processDuration: "3-6 ماه",
        averageCost: "75 EUR",
        visaTypes: ["Family Reunion Visa"],
      },
      {
        id: "self-employment",
        title: "ویزای خوداشتغالی",
        description: "برای افرادی که قصد راه‌اندازی کسب‌وکار در آلمان را دارند.",
        processDuration: "3-6 ماه",
        averageCost: "75 EUR",
        visaTypes: ["Self-Employment Visa"],
        selfEmploymentOptions: "Business plan required",
      },
    ],
    continent: "اروپا",
    capital: "برلین",
    population: "83 میلیون",
    currency: "یورو",
    language: "آلمانی",
    climate: "معتدل",
    socialAmenities: ["Healthcare", "Education", "Public Transport", "Cultural Activities"],
  },
  {
    id: "AUS",
    name: "استرالیا",
    flagUrl: "https://flagcdn.com/au.svg",
    description:
      "استرالیا با طبیعت زیبا، شهرهای پویا و اقتصاد رو به رشد، مقصدی جذاب برای مهاجران است. این کشور برنامه‌های مهاجرتی متنوعی برای کارگران ماهر و سرمایه‌گذاران ارائه می‌دهد.",
    migrationMethods: [
      {
        id: "skilled-migration",
        title: "مهاجرت کاری ماهر",
        description: "برنامه‌های مبتنی بر امتیاز برای کارگران ماهر در مشاغل مورد نیاز.",
        processDuration: "8-15 ماه",
        averageCost: "4,115 AUD",
        visaTypes: ["Skilled Independent Visa (subclass 189)", "Skilled Nominated Visa (subclass 190)"],
        jobOpportunities: ["Healthcare", "IT", "Construction"],
        educationSystem: "High quality, diverse options",
        costOfLiving: "High",
      },
      {
        id: "employer-sponsored",
        title: "ویزای اسپانسرشیپ کارفرما",
        description: "برای افرادی که توسط کارفرمای استرالیایی اسپانسر می‌شوند.",
        processDuration: "6-12 ماه",
        averageCost: "4,115 AUD",
        visaTypes: ["Employer Nomination Scheme (subclass 186)"],
        jobOpportunities: ["Varies by employer"],
      },
      {
        id: "business-innovation",
        title: "ویزای نوآوری و سرمایه‌گذاری تجاری",
        description: "برای کارآفرینان و سرمایه‌گذاران.",
        processDuration: "12-24 ماه",
        averageCost: "6,085 AUD",
        visaTypes: ["Business Innovation and Investment (Provisional) Visa (subclass 188)"],
        startupSupport: "Government grants, incubators",
      },
      {
        id: "student-visa",
        title: "ویزای دانشجویی",
        description: "امکان تحصیل در دانشگاه‌ها و موسسات آموزشی استرالیا.",
        processDuration: "2-4 ماه",
        averageCost: "650 AUD (application fee)",
        visaTypes: ["Student Visa (subclass 500)"],
        jobOpportunities: ["Part-time during study, Post-Study Work Visa"],
        educationSystem: "Globally recognized universities",
        costOfLiving: "High",
      },
      {
        id: "partner-visa",
        title: "ویزای پارتنر",
        description: "برای همسران یا شرکای شهروندان یا مقیمان دائم استرالیا.",
        processDuration: "12-24 ماه",
        averageCost: "7,850 AUD",
        visaTypes: ["Partner Visa (subclass 820/801)"],
      },
    ],
    continent: "اقیانوسیه",
    capital: "کانبرا",
    population: "26 میلیون",
    currency: "دلار استرالیا",
    language: "انگلیسی",
    climate: "متنوع (گرم در شمال، معتدل در جنوب)",
    socialAmenities: ["Healthcare", "Education", "Outdoor Activities", "Multicultural Environment"],
  },
  {
    id: "USA",
    name: "آمریکا",
    flagUrl: "https://flagcdn.com/us.svg",
    description:
      "ایالات متحده آمریکا، سرزمین فرصت‌ها، با اقتصاد بزرگ و متنوع، دانشگاه‌های برتر جهان و فرهنگ پویا، مقصدی جذاب برای مهاجران از سراسر دنیاست.",
    migrationMethods: [
      {
        id: "h1b-visa",
        title: "ویزای H-1B",
        description: "ویزای کار موقت برای متخصصان در مشاغل خاص.",
        processDuration: "6-12 ماه (قرعه‌کشی)",
        averageCost: "1,500 - 7,000 USD",
        visaTypes: ["H-1B Visa"],
        jobOpportunities: ["IT", "Engineering", "Healthcare", "Finance"],
        educationSystem: "World-leading universities",
        costOfLiving: "High",
      },
      {
        id: "eb-visa",
        title: "ویزاهای مبتنی بر اشتغال (EB)",
        description: "ویزاهای اقامت دائم برای کارگران ماهر، متخصصان و سرمایه‌گذاران.",
        processDuration: "1-5 سال",
        averageCost: "3,450 USD (filing fees)",
        visaTypes: ["EB-1", "EB-2", "EB-3", "EB-4", "EB-5"],
        jobOpportunities: ["High-demand sectors"],
      },
      {
        id: "f1-visa",
        title: "ویزای F-1 (دانشجویی)",
        description: "برای تحصیل در دانشگاه‌ها و موسسات آموزشی آمریکا.",
        processDuration: "1-3 ماه",
        averageCost: "200 USD (SEVIS fee) + 160 USD (application fee)",
        visaTypes: ["F-1 Visa"],
        jobOpportunities: ["Limited part-time, OPT/CPT after graduation"],
        educationSystem: "Globally renowned universities",
        costOfLiving: "High",
      },
      {
        id: "eb5-investor",
        title: "ویزای سرمایه‌گذاری EB-5",
        description: "اقامت دائم از طریق سرمایه‌گذاری قابل توجه در کسب‌وکارهای آمریکایی.",
        processDuration: "2-4 سال",
        averageCost: "900,000 - 1,800,000 USD (investment)",
        visaTypes: ["EB-5 Visa"],
        startupSupport: "Access to large market",
      },
      {
        id: "family-based",
        title: "ویزاهای خانوادگی",
        description: "برای پیوستن به شهروندان یا مقیمان دائم آمریکا.",
        processDuration: "1-10 سال (بسته به رابطه)",
        averageCost: "535 USD (filing fee)",
        visaTypes: ["IR-1/CR-1", "F2A/F2B", "F3", "F4"],
      },
    ],
    continent: "آمریکای شمالی",
    capital: "واشنگتن دی‌سی",
    population: "330 میلیون",
    currency: "دلار آمریکا",
    language: "انگلیسی",
    climate: "متنوع",
    socialAmenities: ["Diverse culture", "Innovation hubs", "National Parks"],
  },
  {
    id: "GBR",
    name: "انگلستان",
    flagUrl: "https://flagcdn.com/gb.svg",
    description:
      "انگلستان با تاریخ غنی، شهرهای جهانی و دانشگاه‌های معتبر، مقصدی محبوب برای تحصیل و کار است. پس از برگزیت، سیستم مهاجرتی آن تغییراتی داشته است.",
    migrationMethods: [
      {
        id: "skilled-worker-visa",
        title: "ویزای کارگر ماهر",
        description: "برای افرادی که پیشنهاد شغلی از کارفرمای بریتانیایی دارند.",
        processDuration: "3-8 هفته",
        averageCost: "610 - 1,408 GBP",
        visaTypes: ["Skilled Worker Visa"],
        jobOpportunities: ["Healthcare", "IT", "Finance", "Education"],
        educationSystem: "World-renowned universities",
        costOfLiving: "High",
      },
      {
        id: "student-visa",
        title: "ویزای دانشجویی (Tier 4)",
        description: "برای تحصیل در دانشگاه‌ها و کالج‌های بریتانیا.",
        processDuration: "3-4 هفته",
        averageCost: "348 GBP (application fee)",
        visaTypes: ["Student Visa (Tier 4)"],
        jobOpportunities: ["Part-time during study, Graduate Visa after graduation"],
        educationSystem: "Excellent, globally recognized",
        costOfLiving: "High",
      },
      {
        id: "innovator-visa",
        title: "ویزای نوآور",
        description: "برای کارآفرینانی که ایده‌های تجاری نوآورانه دارند.",
        processDuration: "3-8 هفته",
        averageCost: "1,036 GBP",
        visaTypes: ["Innovator Visa"],
        startupSupport: "Strong startup ecosystem",
      },
      {
        id: "family-visa",
        title: "ویزای خانوادگی",
        description: "برای پیوستن به اعضای خانواده مقیم بریتانیا.",
        processDuration: "2-12 ماه",
        averageCost: "1,523 GBP",
        visaTypes: ["Family Visa"],
      },
    ],
    continent: "اروپا",
    capital: "لندن",
    population: "67 میلیون",
    currency: "پوند استرلینگ",
    language: "انگلیسی",
    climate: "معتدل و مرطوب",
    socialAmenities: ["Healthcare (NHS)", "Education", "Cultural Heritage", "Public Transport"],
  },
  {
    id: "TUR",
    name: "ترکیه",
    flagUrl: "https://flagcdn.com/tr.svg",
    description:
      "ترکیه با موقعیت جغرافیایی استراتژیک، فرهنگ غنی و هزینه‌های زندگی نسبتاً پایین، مقصدی جذاب برای سرمایه‌گذاری و زندگی است.",
    migrationMethods: [
      {
        id: "citizenship-by-investment",
        title: "شهروندی از طریق سرمایه‌گذاری",
        description: "اخذ شهروندی ترکیه با خرید ملک یا سرمایه‌گذاری.",
        processDuration: "3-6 ماه",
        averageCost: "400,000 USD (minimum investment)",
        visaTypes: ["Citizenship by Investment"],
        startupSupport: "Growing economy",
      },
      {
        id: "residence-permit",
        title: "اقامت توریستی/کوتاه مدت",
        description: "اقامت موقت برای اهداف توریستی یا سایر موارد.",
        processDuration: "1-2 ماه",
        averageCost: "80 USD (fee) + insurance",
        visaTypes: ["Short-term Residence Permit"],
      },
      {
        id: "work-permit",
        title: "اجازه کار",
        description: "برای خارجیانی که در ترکیه مشغول به کار می‌شوند.",
        processDuration: "1-3 ماه",
        averageCost: "1,000 TRY (fee)",
        visaTypes: ["Work Permit"],
        jobOpportunities: ["Tourism", "Textile", "Manufacturing"],
      },
    ],
    continent: "آسیا/اروپا",
    capital: "آنکارا",
    population: "84 میلیون",
    currency: "لیر ترکیه",
    language: "ترکی",
    climate: "متنوع (مدیترانه‌ای، قاره‌ای)",
    socialAmenities: ["Affordable living", "Rich culture", "Tourism"],
  },
  {
    id: "PRT",
    name: "پرتغال",
    flagUrl: "https://flagcdn.com/pt.svg",
    description:
      "پرتغال با آب و هوای دلپذیر، سواحل زیبا و برنامه گلدن ویزا، مقصدی محبوب برای سرمایه‌گذاران و بازنشستگان است.",
    migrationMethods: [
      {
        id: "golden-visa",
        title: "گلدن ویزا",
        description: "اخذ اقامت از طریق سرمایه‌گذاری (خرید ملک، انتقال سرمایه).",
        processDuration: "6-12 ماه",
        averageCost: "280,000 - 500,000 EUR (investment)",
        visaTypes: ["Golden Visa"],
        startupSupport: "EU access",
      },
      {
        id: "d7-visa",
        title: "ویزای D7 (بازنشستگان/درآمد ثابت)",
        description: "برای افرادی با درآمد ثابت غیرفعال که قصد اقامت در پرتغال را دارند.",
        processDuration: "2-3 ماه",
        averageCost: "90 EUR (visa fee)",
        visaTypes: ["D7 Visa"],
      },
      {
        id: "digital-nomad-visa",
        title: "ویزای نوماد دیجیتال",
        description: "برای افرادی که از راه دور کار می‌کنند و قصد اقامت در پرتغال را دارند.",
        processDuration: "1-2 ماه",
        averageCost: "90 EUR (visa fee)",
        visaTypes: ["Digital Nomad Visa"],
      },
    ],
    continent: "اروپا",
    capital: "لیسبون",
    population: "10 میلیون",
    currency: "یورو",
    language: "پرتغالی",
    climate: "مدیترانه‌ای",
    socialAmenities: ["Beaches", "Culture", "Affordable living (compared to Western Europe)"],
  },
  {
    id: "GRC",
    name: "یونان",
    flagUrl: "https://flagcdn.com/gr.svg",
    description:
      "یونان، مهد تمدن غرب، با تاریخ کهن، جزایر زیبا و برنامه گلدن ویزا، مقصدی جذاب برای سرمایه‌گذاران و علاقه‌مندان به فرهنگ است.",
    migrationMethods: [
      {
        id: "golden-visa",
        title: "گلدن ویزا",
        description: "اخذ اقامت از طریق خرید ملک یا سرمایه‌گذاری.",
        processDuration: "3-6 ماه",
        averageCost: "250,000 - 500,000 EUR (minimum investment)",
        visaTypes: ["Golden Visa"],
        startupSupport: "EU access",
      },
      {
        id: "digital-nomad-visa",
        title: "ویزای نوماد دیجیتال",
        description: "برای افرادی که از راه دور کار می‌کنند و قصد اقامت در یونان را دارند.",
        processDuration: "1-2 ماه",
        averageCost: "75 EUR (visa fee)",
        visaTypes: ["Digital Nomad Visa"],
      },
    ],
    continent: "اروپا",
    capital: "آتن",
    population: "10 میلیون",
    currency: "یورو",
    language: "یونانی",
    climate: "مدیترانه‌ای",
    socialAmenities: ["Historical sites", "Islands", "Mediterranean cuisine"],
  },
  {
    id: "ESP",
    name: "اسپانیا",
    flagUrl: "https://flagcdn.com/es.svg",
    description:
      "اسپانیا با فرهنگ پر جنب و جوش، آب و هوای آفتابی و شهرهای زیبا، مقصدی محبوب برای زندگی و سرمایه‌گذاری است.",
    migrationMethods: [
      {
        id: "golden-visa",
        title: "گلدن ویزا",
        description: "اخذ اقامت از طریق سرمایه‌گذاری (خرید ملک، سرمایه‌گذاری در شرکت).",
        processDuration: "3-6 ماه",
        averageCost: "500,000 EUR (minimum investment)",
        visaTypes: ["Golden Visa"],
        startupSupport: "EU access",
      },
      {
        id: "non-lucrative-visa",
        title: "ویزای غیرانتفاعی",
        description: "برای افرادی که درآمد کافی برای زندگی در اسپانیا بدون کار کردن دارند.",
        processDuration: "2-3 ماه",
        averageCost: "80 EUR (visa fee)",
        visaTypes: ["Non-Lucrative Visa"],
      },
      {
        id: "digital-nomad-visa",
        title: "ویزای نوماد دیجیتال",
        description: "برای افرادی که از راه دور کار می‌کنند و قصد اقامت در اسپانیا را دارند.",
        processDuration: "1-2 ماه",
        averageCost: "80 EUR (visa fee)",
        visaTypes: ["Digital Nomad Visa"],
      },
    ],
    continent: "اروپا",
    capital: "مادرید",
    population: "47 میلیون",
    currency: "یورو",
    language: "اسپانیایی",
    climate: "مدیترانه‌ای",
    socialAmenities: ["Vibrant culture", "Beaches", "Gastronomy"],
  },
  {
    id: "AUT",
    name: "اتریش",
    flagUrl: "https://flagcdn.com/at.svg",
    description: "اتریش با مناظر کوهستانی خیره‌کننده، شهرهای تاریخی و کیفیت بالای زندگی، مقصدی عالی برای مهاجرت است.",
    migrationMethods: [
      {
        id: "red-white-red-card",
        title: "کارت قرمز-سفید-قرمز",
        description: "سیستم مبتنی بر امتیاز برای کارگران ماهر.",
        processDuration: "2-4 ماه",
        averageCost: "120 EUR",
        visaTypes: ["Red-White-Red Card"],
        jobOpportunities: ["Tourism", "Engineering", "Healthcare"],
        educationSystem: "High quality",
        costOfLiving: "Moderate to High",
      },
      {
        id: "job-seeker-visa",
        title: "ویزای جستجوی کار",
        description: "امکان ورود به اتریش برای جستجوی کار به مدت 6 ماه.",
        processDuration: "2-3 ماه",
        averageCost: "120 EUR",
        visaTypes: ["Job Seeker Visa"],
        jobSearchVisa: "6-month validity",
      },
    ],
    continent: "اروپا",
    capital: "وین",
    population: "9 میلیون",
    currency: "یورو",
    language: "آلمانی",
    climate: "قاره‌ای معتدل",
    socialAmenities: ["Culture", "Nature", "High quality of life"],
  },
]
